name: 'Trigger Rebuild Pages'
on:
  push:
    branches:
      - master

jobs:
  build-pages:
    name: 'Trigger Rebuild Pages'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
        with:
          path: 'generator'
      - uses: 'actions/checkout@v2'
        with:
          repository: 'vim-jp/slacklog'
          path: 'data'
          ref: 'log-data'
          ssh-key: '${{ secrets.SLACKLOG_SSH_KEY }}'
      - name: 'Trigger'
        run: |
          cd generator/scripts
          BASEURL=/slacklog go run ./main.go generate-html ./config.json ../slacklog_template/ ../../data/slacklog_data/ ../../data/
          cd ..
          cp -r assets favicon.ico ../data
          cd ../data
          rm -fr slacklog_data/ .github/
          touch .nojekyll
          git checkout --orphan=gh-pages --quiet
          git add --all --force
          git config user.email "slacklog@vim-jp.org"
          git config user.name "Slack Log Generator"
          git commit --message='publish' --quiet
          git push --force origin gh-pages
