name: 'Trigger Rebuild Pages'
on:
  push:
    branches:
      - '**'
  workflow_run:
    workflows: ['Update logs']
    types: ['completed']

jobs:
  build-pages:
    name: 'Generate htdocs and Update https://vim-jp.org/slacklog/'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v2'
        with:
          path: 'generator'

      - uses: 'actions/checkout@v2'
        with:
          repository: 'vim-jp/slacklog'
          path: 'data'
          ref: 'log-data'

      - uses: 'actions/checkout@v2'
        with:
          repository: 'vim-jp/slacklog'
          path: 'pages'
          ref: 'gh-pages'
          ssh-key: '${{ secrets.SLACKLOG_SSH_KEY }}'

      - name: 'Generate htdocs'
        run: |
          cp -r data/files/ data/emojis/ pages/
          cd generator
          BASEURL=/slacklog go run . generate-html --filesdir ../pages/files/ --indir ../data/slacklog_data/ --outdir ../pages/
          cp -r assets ../pages/
          # create finger print
          cd ../pages
          find . -type d -name '.git' -prune -o -type f -print0 | xargs -0 md5sum > ../files.txt

      - name: 'Save fingerprint'
        uses: actions/upload-artifact@v2
        with:
          name: fingerprint
          path: files.txt

      - name: 'Update https://vim-jp.org/slacklog/'
        if: github.ref == 'refs/heads/master'
        working-directory: './data'
        run: |
          git add --all --intent-to-add --force
          if git diff --exit-code; then
            echo 'Nothing to update.'
            exit 0
          fi
          git config user.email "slacklog@vim-jp.org"
          git config user.name "Slack Log Generator"
          git commit --all --message 'publish' --quiet
          git push origin gh-pages --quiet
