name: 'Trigger Rebuild Pages'
on:
  push:
    branches:
      - '**'

jobs:
  build-pages:
    name: 'Generate htdocs and Update https://vim-jp.org/slacklog/'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v2'
        with:
          path: 'generator'

      - uses: 'actions/checkout@v2'
        with:
          repository: 'vim-jp/slacklog'
          path: 'data'
          ref: 'log-data'
          ssh-key: '${{ secrets.SLACKLOG_SSH_KEY }}'

      - name: 'Generate htdocs'
        run: |
          cd generator
          BASEURL=/slacklog go run . generate-html scripts/config.json templates/ ../data/slacklog_data/ ../data/
          cp -r assets ../data
          rm -fr ../data/slacklog_data/ ../data/.github/
          touch ../data/.nojekyll
          # create finger print
          cd ../data
          find . -type d -name '.git' -prune -o -type f -print0 | xargs -0 md5sum > ../files.txt

      - name: 'Save fingerprint'
        uses: actions/upload-artifact@v2
        with:
          name: fingerprint
          path: files.txt

      - name: 'Update https://vim-jp.org/slacklog/'
        if: github.ref == 'refs/heads/master'
        run: |
          cd data
          git checkout --orphan=gh-pages --quiet
          git add --all --force
          git config user.email "slacklog@vim-jp.org"
          git config user.name "Slack Log Generator"
          git commit --message='publish' --quiet
          git push --force origin gh-pages
