name: 'Trigger Rebuild Pages'
on:
  push:
    branches:
      - master

jobs:
  build-pages:
    name: 'Trigger Rebuild Pages'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
        with:
          repository: 'vim-jp/slacklog'
          ref: 'master'
          ssh-key: '${{ secrets.SLACKLOG_SSH_KEY }}'
      - name: 'Trigger'
        run: |
          git tag rebuild
          git push origin rebuild
