name: CI

on: [push, pull_request]

env:
  GOPATH: ${{ github.workspace }}/..

jobs:

  gotool:
    name: 'scripts/main.go'
    runs-on: 'ubuntu-latest'

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Go into the Go module directory
      uses: actions/setup-go@v2
      with:
        go-version: 1.x

    - name: Build
      run: cd scripts && go build main.go

    - name: Test
      run: cd scripts && go test ./...
